### ISSUE TITLE
estimation speed

### ISSUE THREAD

**Issue by JulesDoe** [chaneyddtt/Generating-Multiple-Hypotheses-for-3D-Human-Pose-Estimation-with-Mixture-Density-Network#1]
Thanks for your great work!
I have questions regarding the evaluation speed of each step.
How long does the used feature extractor and especially the hypothesis generator take for the calculation?
How does the calculation duration scale with the number of people in the picture?
Which hardware was used?
Thanks in advance!

**Comment by chaneyddtt** [comment]
Hi, 
thanks for your interest in our work. 
The average time for each forward step is around 13ms on 1080Ti GPU. This is calculated when the number of Gaussian kernels is five.
This work focuses on single person 3d pose estimation.  There is only one person in each images of both human3.6m and MPI datasets. For image in MPII dataset where there are multiple persons, we use the stacked hourglass to detect 2d joints for each person, and then generate 3d pose hypotheses based on the 2d joints.
