### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pender** [chaneyddtt/Generating-Multiple-Hypotheses-for-3D-Human-Pose-Estimation-with-Mixture-Density-Network#2]
Thank you so much for sharing your code for your groundbreaking paper! Can I request that you please specify what license the code is available under by [including a License.md file](https://help.github.com/en/articles/adding-a-license-to-a-repository) in the repository?

**Comment by chaneyddtt** [comment]
Thanks a lot for reminding.
