### ISSUE TITLE
How can I test on MPI-INF-3DHP?

### ISSUE THREAD

**Issue by nies14** [chaneyddtt/Generating-Multiple-Hypotheses-for-3D-Human-Pose-Estimation-with-Mixture-Density-Network#20]
Hi @chaneyddtt 
Thanks for the great work.
I have preprocessed the MPI-INF-3DHP Preprocessed data. I Pre-processed that using following script (https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/mpi_inf_3dhp.py).  Now I have 'mpi_inf_3dhp_test.npz'. Now, how can I test on MPI-INF-3DHP using this?

Which keypoints & arguments do I need to pass to test this?

**Comment by chaneyddtt** [comment]
Hi @nies14, thanks for your interests. I used the keypoints [25, 24, 23, 18, 19, 20, 4, 3, 5, 7, 16, 15, 14, 9, 10, 11] of the MPI-INF-3DHP dataset. You can directly test using our pretrained model. Btw, [this issue](https://github.com/chaneyddtt/Generating-Multiple-Hypotheses-for-3D-Human-Pose-Estimation-with-Mixture-Density-Network/issues/12) might be helpful.

**Comment by nies14** [comment]
@chaneyddtt Thanks for the reply. I just have 2 queries

1. Which arguments should be passed and what should be the value of those arguments to test it on MPI-INF-3DHP? Could you please give me any sample?
2. Which script/repo did you follow to pre-process the MPI-INF-3DHP data?

**Comment by chaneyddtt** [comment]
Hi @nies14, the MPI-INF-3DHP dataset is pre-processed in the same way as the Human3.6M, namely centralize with the root joint and then normalize. I wrote the pre-precess code following the Human3.6M. After that you can test with the same command as the one we use for Human3.6.

**Comment by nies14** [comment]
Hi @chaneyddtt Thanks a lot for the reply. Could u please give me your pre-processing script?

If u can't provide that then could you please provide the orginal script link u followed to make the mpi-inf-3dhp pre-processing script?

**Comment by nies14** [comment]
Hi  @chaneyddtt Thanks a lot for the reply. Could u please give me your pre-processing script?

If u can't provide that then could you please provide the orginal script link u followed to 
make the mpi-inf-3dhp pre-processing script?

**Comment by chaneyddtt** [comment]
I did not follow any link since I did not find it back then. I did not clean up the code for this part, so it is a bit messy. Can you give me your email address if you want the script?

**Comment by nies14** [comment]
@chaneyddtt thanks so much for that

mthnies@gmail.com

**Comment by Bingo-1996** [comment]
Hi, @chaneyddtt, can you send the pre-processing script to me? I have tried this dataset for a long time without success.
Thank you very much!!!

lzou@mail.ustc.edu.cn

**Comment by XuyangHao123** [comment]
> I did not follow any link since I did not find it back then. I did not clean up the code for this part, so it is a bit messy. Can you give me your email address if you want the script?

Could u please mail me your preprocess scrips on mpi inf 3dhp?
1499703595@qq.com
thanks so much🙏🏻🙏🏻🙏🏻

**Comment by nies14** [comment]
> > I did not follow any link since I did not find it back then. I did not clean up the code for this part, so it is a bit messy. Can you give me your email address if you want the script?
> 
> Could u please mail me your preprocess scrips on mpi inf 3dhp? [1499703595@qq.com](mailto:1499703595@qq.com) thanks so much🙏🏻🙏🏻🙏🏻

You can follow this repo [MLP-Graph](https://github.com/nies14/Spatio-Temporal-MLP-Graph)
